# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: https://somayej.github.io/
email: sumaye.jafarie@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Somaye Jafaritazehjanis personal and professional website
# twitter_username: username
github_username: somayeJ
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Stockholm # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Somayeh Jafari"
  avatar: "/assets/images/sj.jpg"
  bio: "PhD graduate of Natural Language Processing, Machine Learning and AI."
  links:
    - label: "sumaye.jafarie@gmail.com"
      icon: "fab fa-fw fa-regular fa-envelope"
      url: "mailto:sumaye.jafarie@gmail.com"
    - label: "G Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=oXyz8zgAAAAJ&hl=sv&oi=ao"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/somayeJ?tab=repositories"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/somayeh-jafaritazehjani-5ba84397/"

footer:
  links:
    - label: "sumaye.jafarie@gmail.com"
      icon: "fab fa-fw fa-regular fa-envelope"
      url: "mailto:sumaye.jafarie@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/somayeJ?tab=repositories"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/somayeh-jafaritazehjani-5ba84397/"

defaults:
  # _posts
  # - scope:
  #    path: ""
  #    type: posts
  #  values:
  #    layout: single
  #    author_profile: true
  #    read_time: true
  #    comments: true
  #    share: true
  #    related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
